### ISSUE TITLE
Location of config attributes

### ISSUE THREAD

**Issue by richardhauer** [chrispadgettlivecom/active-directory-b2c-custom-policy-samples#7]
Could you please identify the source of the configuration attributes required by `local.json`.

The `IdentityExperienceFrameworkApplicationAppId` and `your-tenant-name.onmicrosoft.com` are self-explanatory, but I could not find anything in the Azure portal that might qualify as a value for the `Proxy IEF AppId` or `IEF Extension Application` - there does not seem to be any mention of these anywhere from what I can see, so a little guidance would be appreciated.

PS. Complete n00b at this so apologies if the answer is staring me in the face.

**Comment by chrispadgettlivecom** [comment]
Hi @richardhauer 

`iefExtensionApplication` is referring to the **b2c-extensions-app** application that is created by Microsoft in your Azure AD B2C tenant (see https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-extensions-app).

`iefAuthenticationApplication` and `iefAuthenticationProxyApplication` are referring to the **IdentityExperienceFramework** and **ProxyIdentityExperienceFramework** applications that are created by you in your Azure AD B2C tenant (see https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-get-started-custom?tabs=applications#register-identity-experience-framework-applications).

**Comment by richardhauer** [comment]
Thanks @chrispadgettlivecom !

I came into the configuration process with a number of components already in place, so I wasn't aware of these elements.

I have learned a lot from your samples!  Thanks again.
